apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-deployment
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 1
  template:
    metadata:
      labels:
        app: myapp
    spec:
     containers:
      - name: service
        image: guijiedocker/healthy:healthy-v4
        ports:
        - containerPort: 8080

        livenessProbe:
            httpGet:
                path: /healthy
                port: 8080
            initialDelaySeconds: 3
            periodSeconds: 3
